### ISSUE TITLE
Cannot extend Headings.yml

### ISSUE THREAD

**Issue by amyq** [errata-ai/Microsoft#16]
I'm attempting to create a company-specific version of https://github.com/errata-ai/Microsoft/blob/master/Microsoft/Headings.yml and I'm finding that if …

* I create a company-specific file (``acquia/Headings.yml``) in our style folder
* I leave both ``microsoft/Headings.yml`` and ``acquia/Headings.yml`` enabled

… the words in ``microsoft/Headings.yml`` are treated as exceptions, but words in ``acquia/Headings.yml`` are not, unless I add ``microsoft.Headings = NO`` to _vale.ini

(The 'microsoft' style is called before the 'acquia' style in _vale.ini, if that's useful)

Here's the first 12 lines from our acquia/Headings.yml file:

```
extends: capitalization
message: "'%s' should use sentence-style capitalization."
level: suggestion
scope: heading
match: $sentence
exceptions:
  - Academy
  - Acquia
  - Cloud
```

When I disable the Microsoft file, this subheading is (correctly) allowed:

```
Evaluating Acquia Cloud
-----------------------
```

**Comment by jdkato** [comment]
Exceptions are only considered for the rule they're listed in -- in other words, `microsoft.Headings` respects the exceptions in its own file, but doesn't consider those listed in `acquia.Headings`.

So, if you have both `microsoft.Headings` and `acquia.Headings` enabled, the expected result is for `microsoft.Headings` to complain while `acquia.Headings` does not:

```console
 test.md
 1:1  suggestion  'Evaluating Acquia Cloud'       microsoft.Headings 
                  should use sentence-style                          
                  capitalization.  
```

**Comment by amyq** [comment]
Ah - I assumed they would be treated as additive, since they were both extensions of the `capitalization` rule.

**Comment by wouter-veeken** [comment]
@jdkato For the spellchecker, one can reference an external .txt with exceptions. Would a similar thing work for this?

**Comment by jdkato** [comment]
I'm not sure that I understand the goal here.

If `microsoft.Headings` and `acquia.Headings` did indeed respect each other's exceptions, you'd *always* receive duplicates alerts: anytime a heading violated one rule, it'd also violate the other. Essentially, you would have implemented the same rule twice.

The same issue would exist if both `microsoft.Headings` and `acquia.Headings` referenced the same external ignore file, as suggested above.

**Comment by wouter-veeken** [comment]
Durr, you're right. 🤔

So I suppose the only sane solution in this scenario is to have a single catch-all check?

**Comment by amyq** [comment]
I think so. It's understandable, but disappointing; our corporate style *starts* with the Microsoft style guide, then layers industry- and company-specific style expectations atop it. We were hoping to keep importing the MS style without modifying those files, and keep our company-specific styles out of it.

**Comment by jdkato** [comment]
Admittedly, I think the notion of customizing a "third-party" style (i.e., one that technically neither Vale nor the active user created) is one of Vale's weaker points at the moment. (FWIW, this is something that I've [addressed in Vale Server](https://medium.com/@jdkato/introducing-vale-server-36264789d89#ca90)). 

However, I think the way styles *interact* with each other is an entirely different issue and is handled fairly well currently. There's no way that some kind of inheritance system involving intermixing of exceptions between styles could work. In addition to the duplication issue mentioned above, it's quite possible that rules extending the same point (e.g., `capitalization`) expect the opposite exceptions: for example, `microsoft.Headings` could want _sentence case_, while `some-style.Headings` wants _title case_.

---

That said, here's what I would do:

1. In your `.vale.ini` file, I'd use both styles as a base:

    ```ini
    StylesPath = path/to/some/directory
    MinAlertLevel = suggestion

    [*.md]
    BasedOnStyles = Microsoft, Acquia
    ```
2. Whenever you encounter a rule that doesn't work with the in-house style or terminology, I'd change it in the custom style:

    ```ini
    StylesPath = path/to/some/directory
    MinAlertLevel = suggestion

    [*.md]
    BasedOnStyles = Microsoft, Acquia

    # Disabled in favor of Acquia.Headings, which has an exception's list
    # tailored to Acquia's content.
    Microsoft.Headings = NO
    ```
    In practice, you should only need to do this when either your custom style diverges from Microsoft or your exceptions (`conditional` and `capitalization` rules) do.

This ensures that you have "data hygiene" both ways: `Microsoft` doesn't care about `Acquia`'s exceptions or non-MS guidelines, and `Acquia` only cares about its guidelines that aren't already covered (adequately) in `Microsoft`.

**Comment by jdkato** [comment]
I'm going to close this for now -- but if anyone has any ideas for improving my suggested workflow, feel free to comment further.

**Comment by bdovaz** [comment]
> Admittedly, I think the notion of customizing a "third-party" style (i.e., one that technically neither Vale nor the active user created) is one of Vale's weaker points at the moment. (FWIW, this is something that I've [addressed in Vale Server](https://medium.com/@jdkato/introducing-vale-server-36264789d89#ca90)).
> 
> However, I think the way styles _interact_ with each other is an entirely different issue and is handled fairly well currently. There's no way that some kind of inheritance system involving intermixing of exceptions between styles could work. In addition to the duplication issue mentioned above, it's quite possible that rules extending the same point (e.g., `capitalization`) expect the opposite exceptions: for example, `microsoft.Headings` could want _sentence case_, while `some-style.Headings` wants _title case_.
> 
> That said, here's what I would do:
> 
> 1. In your `.vale.ini` file, I'd use both styles as a base:
>    ```ini
>    StylesPath = path/to/some/directory
>    MinAlertLevel = suggestion
>    
>    [*.md]
>    BasedOnStyles = Microsoft, Acquia
>    ```
> 2. Whenever you encounter a rule that doesn't work with the in-house style or terminology, I'd change it in the custom style:
>    ```ini
>    StylesPath = path/to/some/directory
>    MinAlertLevel = suggestion
>    
>    [*.md]
>    BasedOnStyles = Microsoft, Acquia
>    
>    # Disabled in favor of Acquia.Headings, which has an exception's list
>    # tailored to Acquia's content.
>    Microsoft.Headings = NO
>    ```
>    
>    
>        
>          
>        
>    
>          
>        
>    
>        
>      
>    In practice, you should only need to do this when either your custom style diverges from Microsoft or your exceptions (`conditional` and `capitalization` rules) do.
> 
> This ensures that you have "data hygiene" both ways: `Microsoft` doesn't care about `Acquia`'s exceptions or non-MS guidelines, and `Acquia` only cares about its guidelines that aren't already covered (adequately) in `Microsoft`.

@jdkato this is still the same as far as I can see, isn't it?

I mean, if I want to add an acronym that is not in this listing:

https://github.com/errata-ai/Microsoft/blob/master/Microsoft/Acronyms.yml

Ideally I would like to be able to “extend” this rule and be able to add additively more “exceptions”.

Now I see that there are only 2 options:
1. Create a Vocab with an accept.txt that includes my acronyms: this has the problem that the Vocab are global, not specific to a rule. That is, I would like to be able to add the exception for a specific rule, not globally.
2. Duplicate that yml and create my own style adding in exceptions my acronyms: the problem in this case is that if the original yml is changed, it would be out of sync with mine.
